blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('blog-detail/<int:pk>/',
          views.BlogDetail.as_view(), name='detail_blog'),
    path('tech-list/',
         views.TechView.as_view(), name='tech_list'),
    path('dailylife-list/',
         views.DailylifeView.as_view(), name='dailylife_list'),
    path('hobby_list/',
         views.HobbyView.as_view(), name='hobby_list'),
]

firstproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] 

blog/models.py
from django.db import models

# Create your models here.

class BlogPost(models.Model):
    # カテゴリに登録する項目をタプルで定義
    CATEGORY=(('dailylife', '日常のこと'), ('tech', '技術的なこと'), ('hobby', '趣味のこと'))

    title = models.CharField(max_length=200, verbose_name='タイトル')
    content = models.TextField(verbose_name='本文')
    posted_at = models.DateTimeField(verbose_name='投稿時間', auto_now_add=True)
    category = models.CharField(verbose_name='カテゴリー', choices=CATEGORY, max_length=50)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from .models import BlogPost

class IndexView(ListView):
    """トップページのビュー
    テンプレートのレンダリングに特化したTemplateViewを継承

    Attributes:
        template_name:レンダリングするテンプレート
        context_object_name: object_listキーの別名を設定
        queryset: データベースのクエリ
    """
    # index.htmlをレンダリングする
    template_name = 'index.html'
    # object_listの別名を定義
    context_object_name = 'Orderby_records'
    # モデルBlogPostのオブジェクトにorder_by()を適用して
    # BlogPostのレコードを投稿日時の降順で並び替える
    queryset = BlogPost.objects.order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 4

class BlogDetail(DetailView):
    """
    投稿記事の詳細を表示するのでDetailViewを継承する
    Attributes;
      template_name: レンダリングするテンプレート
      Model: モデルのクラス
    """
    # post.htmlをレンダリングする
    template_name = 'post.html'
    # クラス変数modelにBlogPostを設定
    model = BlogPost

class TechView(ListView):
    """
    技術的なこと(tech)カテゴリの記事を一覧するビュー
    """
    template_name = 'tech_list.html'
    model = BlogPost

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:index' %}">OOOODDYのブログ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header>{% block header %}{% endblock %}</header>
        <!-- Main Content-->
         {% block contents %}{% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://twitter.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://facebook.com">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://github.co.jp/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; BBlog 2024</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

blog/templates/dailylife_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}OOOODDYのブログ - DailyLife{% endblock %}
{% block header %}
<!-- Page Header-->
<header class="masthead" style="background-image: url( 'static/assets/img/home-bg.jpg' )">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>OOOODDYのブログ</h1>
                    <span class="subheading">日常のブログ</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block contents %}
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
                {% for record in dailylife_records %}
            <div class="post-preview">
                <a href="{% url 'blog:detail_blog' record.pk %}">
                    <h2 class="post-title">{{ record.title }}</h2>
                    <h3 class="post-subtitle">
                        <span style="font-size: 16pt;">
                            {{ record.content|truncatechars:50}}
                        </span>
                    </h3>
                </a>
                <p class="post-meta">
                    <a href="#">OOOODDYのブログ</a>
                    {{ record.posted_at }}にpost/カテゴリ:
                    {{ record.category }}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}
            <!-- Pager-->
            <!-- ページネーションの組み込み -->
            {% include 'pagination.html' %}
        </div>
    </div>
</div>
<hr class="my-4" />
{% endblock %}

blog/templates/hobby_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblockOOOODDYのブログ - Hobby %}
{% block header %}
<!-- Page Header-->
<header class="masthead" style="background-image: url( 'static/assets/img/home-bg.jpg' )">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>OOOODDYのブログ</h1>
                    <span class="subheading">趣味ブログ</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block contents %}
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
                {% for record in hobby_records %}
            <div class="post-preview">
                <a href="{% url 'blog:detail_blog' record.pk %}">
                    <h2 class="post-title">{{ record.title }}</h2>
                    <h3 class="post-subtitle">
                        <span style="font-size: 16pt;">
                            {{ record.content|truncatechars:50}}
                        </span>
                    </h3>
                </a>
                <p class="post-meta">
                    <a href="#">OOOODDYのブログ</a>
                    {{ record.posted_at }}にpost/カテゴリ:
                    {{ record.category }}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}
            <!-- Pager-->
            <!-- ページネーションの組み込み -->
            {% include 'pagination.html' %}
        </div>
    </div>
</div>
<hr class="my-4" />
{% endblock %}

blog/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>OOOODDYblog</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'blog:index' %}">OOOODDYのブログ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url( 'static/assets/img/home-bg.jpg' )">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>OOOODDYblog</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                     {% for record in Orderby_records %}
                    <div class="post-preview">
                        <a href="{% url 'blog:detail_blog' record.pk %}">
                            <h2 class="post-title">{{ record.title }}</h2>
                            <h3 class="post-subtitle">
                                <span style="font-size: 16pt;">
                                    {{ record.content|truncatechars:50}}
                                </span>
                            </h3>
                        </a>
                        <p class="post-meta">
                            <a href="#!">OOOODDYblog</a>
                            {{ record.posted_at }}にpost/カテゴリ:
                            {{ record.category }}
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                    {% endfor %}
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://twitter.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://facebook.com">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://github.co.jp/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; BBlog 2024</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

blog/templates/pagination.html
<!-- is_paginated表示結果が分割されているかどうかを示すブール値
 オブジェクトの工数がpaginate_byと等しいか、それ以下の場合にはFalseがセットされる -->
{% if is_paginated %}
  <ul class="pagination" style="justify-content: center;">
  <!-- 前ページへのリンク　page.has_previous:前ページがある場合にTrueを返す -->
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous" class="page-link">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}
    <!-- ページ数の表示　pagi nator.page_range:[1, 2, 3, 4]のように1から始まる番号 -->
    {% for num in paginator.page_range %}
    <!-- ページ番号が存在しない場合
      page.number:1から数えたページ番号 -->
      {% if page_obj.number == num %}
        <li class="page-item active">
          <span class="page-link">{{ num }}</span>
        </li>
        {% else %}
        <li class="page-item">
          <a href="?page={{ num }}" class="page-link">{{ num }}</a>
        </li>
      {% endif %}
    {% endfor %}
    <!-- 次のページがある場合にTrueを返す -->
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next" class="page-link">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% endif %}
  </ul>
{% endif %}

blog/templates/post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}OOOODDYblog{% endblock %}
{% block header %}
<!-- Page Header-->
<header class="masthead" style="background-image: url( 'static/assets/img/post-bg.jpg' )">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>{{ object.title }}</h1>
                    <h2 class="subheading">{{ object.body|truncatechars:30 }}</truncatechars:30></h2>
                    <span class="meta">
                        <a href="#!">{% url 'blog:index' %}</a>
                        {{ object.posted_at }}にpost/カテゴリ:
                        {{ object.category }}
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block contents %}
<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>{{ object.content }}</p>
            </div>
        </div>
    </div>
</article>
<hr>
{% endblock %}

blog/templates/tech_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}OOOODDYのブログ - Tech{% endblock %}
{% block header %}
<!-- Page Header-->
<header class="masthead" style="background-image: url( 'static/assets/img/home-bg.jpg' )">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>OOOODDYのブログ</h1>
                    <span class="subheading">Techブログ一覧</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{% block contents %}
<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
                {% for record in tecf_records %}
            <div class="post-preview">
                <a href="{% url 'blog:detail_blog' record.pk %}">
                    <h2 class="post-title">{{ record.title }}</h2>
                    <h3 class="post-subtitle">
                        <span style="font-size: 16pt;">
                            {{ record.content|truncatechars:50}}
                        </span>
                    </h3>
                </a>
                <p class="post-meta">
                    <a href="#">OOOODDYのブログ</a>
                    {{ record.posted_at }}にpost/カテゴリ:
                    {{ record.category }}
                </p>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
            {% endfor %}
            <!-- Pager-->
            <!-- ページネーションの組み込み -->
            {% include 'pagination.html' %}
        </div>
    </div>
</div>
<hr class="my-4" />
{% endblock %}